### ISSUE TITLE
Pointer to database not disassociated after closing database

### ISSUE THREAD

**Issue by MysticElectron** [interkosmos/fortran-sqlite3#4]
I noticed that the pointer to the database seems not to be disassociated after closing the database.
If I do
`rc = sqlite3_close(db)`
then rc is `SQLITE_OK`
but a `c_associated(db)` afterwards still returns `.TRUE.`
This makes it impossible to open the same or another SQLite database after closing a database.

**Comment by interkosmos** [comment]
I cannot reproduce this behaviour with the master branch, i.e., `c_associated(db)` returns ~`.true.`~ `.false.` after calling `sqlite3_close(db)`. Do you use an older version of the library?

**Comment by MysticElectron** [comment]
Just updated to version 3.42.0 of SQLite and now using the latest version of your files.
Still, the `c_associated(db) `is `.true.` after the closing call.

However, I found out that I can reopen the SQLite database afterwards or open another one as long as I do not call the `sqlite3_config()` routines again. So I can open multiple SQLite databases without having to close the program, which is the most important point for me. I can live with the situation as it is now.

One cause for this behaviour might be that I am using your routines in a Windows environment which is a bit older (Visual Studio 2013 and Intel Fortran 2017).

**Comment by interkosmos** [comment]
In this case, `sqlite3_close()` should return a SQLite error code. You can print the last error message with:

```fortran
print *, sqlite3_errmsg(db)
```
