### ISSUE TITLE
SQLiteCiper

### ISSUE THREAD

**Issue by tkdhss111** [interkosmos/fortran-sqlite3#5]
Dear interkosmos,

Can you add interfaces below for SQLiteCiper?

int sqlite3_key(
  sqlite3 *db,                   /* Database to be keyed */
  const void *pKey, int nKey     /* The key, and the length of the key in bytes */
);
int sqlite3_key_v2(
  sqlite3 *db,                   /* Database to be keyed */
  const char *zDbName,           /* Name of the database */
  const void *pKey, int nKey     /* The key */
);

Best,
Hisashi

**Comment by interkosmos** [comment]
SQLiteCiper seems to be a distinct product based on SQLite. I don’t think this repository is the right place for non-vanilla interfaces. I haven’t tested it, but the following interfaces should do it:
```fortran
interface
    function sqlite3_key(db, pkey, nkey) bind(c, name='sqlite3_key')
        import :: c_char, c_int, c_ptr
        implicit none
        type(c_ptr),            intent(in), value :: db
        character(kind=c_char), intent(in)        :: pkey
        integer(kind=c_int),    intent(in), value :: nkey
        integer(kind=c_int)                       :: sqlite3_key
    end function sqlite3_key

    function sqlite3_key_v2(db, zdbname, pkey, nkey) bind(c, name='sqlite3_key_v2')
        import :: c_char, c_int, c_ptr
        implicit none
        type(c_ptr),            intent(in), value :: db
        character(kind=c_char), intent(in)        :: zdbname
        character(kind=c_char), intent(in)        :: pkey
        integer(kind=c_int),    intent(in), value :: nkey
        integer(kind=c_int)                       :: sqlite3_key_v2
    end function sqlite3_key_v2
end interface
```
The passed `zdbname` has to be null-terminated.

**Comment by tkdhss111** [comment]
Dear Phillip,

Thank you for sending me Fortran interfaces!
I will test this.

Best,
Hisashi

2023年10月11日(水) 4:32 Philipp ***@***.***>:

**Comment by tkdhss111** [comment]
Thank you, it works fine.
