### ISSUE TITLE
sqlite3 dose not work with intel fortran 2020

### ISSUE THREAD

**Issue by zangmolk** [interkosmos/fortran-sqlite3#6]
I use Intel Fortran 2020 with visual studio 2019. when I build this project, I got this error:
error LNK2019: unresolved external symbol _sqlite3_open_v2 referenced in function _SQLITE3_mp_SQLITE3_OPEN_V2		sqlite3.obj		

Have anyone idea about this error?

**Comment by interkosmos** [comment]
What SQLite version do you use?

**Comment by zangmolk** [comment]
I use sqlite3.

**Comment by interkosmos** [comment]
I meant the subversion of SQLite 3, for instance:

```
$ sqlite3 --version
3.45.0 2024-01-15 17:01:13 1066602b2b1976fe58b5150777cced894af17c803e068f5918390d6915b4alt1 (64-bit)
```

**Comment by zangmolk** [comment]
I use the latest version.
3.45.1 2024-01-30 16:01:20 e876e51a0ed5c5b3126f52e532044363a014bc594cfefa87ffb5b82257cc467a (64-bit)

**Comment by interkosmos** [comment]
I’ve added some macro wrappers to fix the ABI-related bugs, and tested it with Intel oneAPI 2024 on Linux:

```
$ make test CC=icx FC=ifx
icx -O2 -march=native -c src/sqlite3_macro.c
ifx -O2 -march=native -c src/sqlite3_util.f90
ifx -O2 -march=native -c src/sqlite3.f90
ar rcs libfortran-sqlite3.a sqlite3.o sqlite3_macro.o sqlite3_util.o
ifx -O2 -march=native -I/usr/local/include -L/usr/local/lib -o test_sqlite3 test/test_sqlite3.f90 libfortran-sqlite3.a -lsqlite3

$ ./test_sqlite3
SQLite library version: 3.40.1
SQLite source ID: 2022-12-28 14:03:47 df5c253c0b3dd24916e4ec7cf77d3db5294cc9fd45ae7b9c5e82ad8197f3alt1
DB name: main
...
```
