### ISSUE TITLE
sqlite3 not working with ubuntu and gfortran

### ISSUE THREAD

**Issue by zepholus** [interkosmos/fortran-sqlite3#7]
When running 
``` gfortran -o example example.f90 libfortran-sqlite3.a -lsqlite3``` ,
I'm getting the following error:
``` 
/usr/bin/ld: libfortran-sqlite3.a(sqlite3.o): in function `__sqlite3_MOD_sqlite3_db_name':                                          
sqlite3.f90:(.text+0x4a1): undefined reference to `sqlite3_db_name'         collect2: error: ld returned 1 exit status 
``` 
I'm running this on Ubuntu, and my sql version is 3.41.2.

Apart from that, the only command i haven't executed is ``` pkg install databases/sqlite3```, instead i run ``` sudo apt-get install -y libsqlite3-dev```.

**Comment by interkosmos** [comment]
The SQLite function `sqlite3_db_name()` was introduced in version 3.39 ([release notes](https://www.sqlite.org/releaselog/3_39_0.html)). I’ve tested it on Debian 6.1, using GNU Fortran 12.2 and SQLite 3.40.1. I cannot reproduce this issue. Are you sure the SQLite library you link against is 3.41.2?

**Comment by zepholus** [comment]
So now I have uninstalled the older version of sqlite, download and compiled the newer one (3.45), and now I can run your example. The problem now is that the sqlite file is created:

![imagen](https://github.com/interkosmos/fortran-sqlite3/assets/49274979/a3a5430f-308f-4755-8bee-92ec87c4343d)

But then when executing this chunk of code:

```
    ! Run the statement.
    rc = sqlite3_step(stmt)
    if (rc /= SQLITE_DONE) print '("sqlite3_step(): failed")'
```

It doesn't work (I'm getting as output sqlite3_step(): failed, and nothing is inserted on the table.

Besides, how can bulk insert can be done using this library?

Thanks,

**Comment by interkosmos** [comment]
The error indicates a (write) permission error. Make sure the owner of the program has write permission to the database (use `chmod` or `chown`). You can output the error message instead:

```fortran
rc = sqlite3_step(stmt)
if (rc /= SQLITE_DONE) then
    print '("Error: ", a)', sqlite3_errmsg(db)
end if
```

To bulk insert records into a database, follow:

1. Prepare the statement with `sqlite3_prepare_v2()`.
2. Bind the values with `sqlite3_bind_*()` to the statement.
3. Execute the statement with `sqlite3_step()`.
4. Reset the statement with `sqlite3_reset()`.
5. Repeat from step 2 onwards until all records are inserted.
6. Clear the statement with `sqlite3_finalize()`.

**Comment by zepholus** [comment]
Solved, thx 👍
